services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - .:/app # live code reload support

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
