name: Deploy to VPS

on:
  push:
    branches:
      - client-p1  # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Use SSH Action to connect to your VPS
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}          # e.g., "123.45.67.89" or your domain
          username: ${{ secrets.VPS_USER }}       # the non-root user you created, e.g., "deploy"
          key: ${{ secrets.VPS_SSH_KEY }}         # your private SSH key (stored as a GH secret)
          # passphrase: ${{ secrets.VPS_PASSPHRASE }}  # if your SSH key is passphrase-protected
          script: |
            cd /home/fuksi-client/fuksiseikkailu/client
            git pull origin client-p1
            npm install
            npm test
            npm run build
